### PR TITLE
Fix CI unit test

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**

### CODE REVIEW

**Comment by shubham-pampattiwar** [comment]
Reference PR: https://github.com/openshift/oadp-operator/pull/1375/files

**Review by mateusoliveira43 — APPROVED** [review]
/lgtm

**Comment by shubham-pampattiwar** [comment]
Unblocks the CVE fix PR: https://github.com/openshift/openshift-velero-plugin/pull/242

**Review by kaovilai — APPROVED** [review]

**Pull request merged**
